# Generated by Django 5.0.4 on 2024-04-27 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexo', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('estado_salud', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Gato',
            fields=[
                ('animal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='App.animal')),
                ('color_pelo', models.CharField(max_length=100)),
               
            ],
            bases=('App.animal',),
        ),
        migrations.CreateModel(
            name='Perro',
            fields=[
                ('animal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='App.animal')),
                ('raza', models.CharField(max_length=100)),
                
            ],
            bases=('App.animal',),
        ),
    ]
