# Generated by Django 5.0.4 on 2024-04-28 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='descripcion',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='animal',
            name='estado_salud',
            field=models.TextField(max_length=300),
        ),
    ]
